key:
    config:
      auth: http://localhost:8081/auth/exit
server:
    port: 8082
    servlet:
     context-path: /ui
     session:
      cookie:
        name: UISESSION
spring:
  thymeleaf:
    cache: false
    suffix: .html
    encoding: UTF-8
  messages:
    basename: messages
    fallbackToSystemLocale: false
  data:
    mongodb:
      database: testdb
      host: ec2-52-221-188-131.ap-southeast-1.compute.amazonaws.com
      port: 27017
      username: karson
      password: karson
  security:
    user:
      name: ry
      password: ry