key:
    config:
      auth: http://localhost:8081/auth/exit
server:
    port: 8082
    servlet:
     context-path: /ui
     session:
      cookie:
        name: UISESSION
spring:
  thymeleaf:
    cache: false
    suffix: .html
    encoding: UTF-8
  messages:
    basename: messages
    fallbackToSystemLocale: false
  data:
    mongodb:
      database: school
      uri: mongodb://ec2-18-188-86-209.us-east-2.compute.amazonaws.com:27017

  security:
    user:
      name: ry
      password: ry